# Firebase Admin SDK service account key file
firebase.service.account.key=classpath:firebase-service-account.json

# Firestore settings (if needed)
spring.cloud.gcp.firestore.project-id=schoolscheduler-fa641